fix(cli): capacitor recognize multi-project
ionic-team/ionic-cli pull request #4937
Opened 2022-12-14 06:27 UTC by IT-MikeS

2022-12-15 18:44 UTC, giralte-ionic approved these changes

2022-12-16 17:44 UTC, jcesarmobile requested changes

2022-12-16 17:44 UTC, jcesarmobile commented on packages/@ionic/cli/src/lib/integrations/capacitor/index.ts
> +    // const output = await this.e.shell.cmdinfo('capacitor', args, { cwd: this.root });
```suggestion
```
remove the commented line

2022-12-16 17:44 UTC, jcesarmobile commented on packages/@ionic/cli/src/lib/integrations/capacitor/index.ts
> +        return '';
shouldn't it return something?
In example if I uninstall @capacitor/cli when it runs `capacitor sync android` I just get
```
Error

at new SubprocessError
...
(stack trace of files and lines)
```

2022-12-20 09:02 UTC, jcesarmobile approved these changes

2022-12-20 15:44 UTC, merged