fix(cli): resolve vm2 security vulnerability
ionic-team/ionic-cli pull request #5070
Opened 2023-12-14 18:20 UTC by sean-perkins

Ionic CLI currently has a severe security vulnerability with the `vm2` dependency as a result of `superagent-proxy` → `proxy-agent. 

The [`superagent-proxy`](https://github.com/TooTallNate/superagent-proxy) package is a smaller wrapper around `proxy-agent` that is not maintained. 

This PR removes the dependency for `superagent-proxy`  and upgrades to `proxy-agent@6` which no longer has the `vm2` dependency requirement. The `proxy-agent` package uses ESM & as a result a lot of other usages had to be migrated once `esmoduleInterop` was enabled. The proxy behavior that `superagent-proxy` was responsible for has been added here: https://github.com/ionic-team/ionic-cli/blob/5b8e061df37e3cd841fbdf49880f0db1905de764/packages/%40ionic/cli/src/lib/utils/superagent-proxy.ts. 

There is quite a bit of runtime risk with these changes that we need to test extensively. For example in testing I had missed migrating:
```
import * as chalk from 'chalk';
```

& the build still passed compilation/transformation. However at runtime an exception was thrown.

2023-12-14 20:44 UTC, ltm approved these changes

2023-12-14 22:06 UTC, thetaPC requested changes

2023-12-14 22:06 UTC, thetaPC commented on packages/@ionic/cli/ionic-cli-7.1.5.tgz
Remove this zip.

2023-12-18 18:17 UTC, thetaPC requested changes

2023-12-18 18:17 UTC, thetaPC commented on packages/@ionic/cli/.gitignore
> +*.tgz
```suggestion
*.tgz

```
Missing new line

2023-12-18 18:58 UTC, thetaPC approved these changes
LGTM

2023-12-19 16:31 UTC, merged